# Data Catalog Smart testing
commit_dataset:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/raw_data/commits.csv

project_wrapper:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/models/project_wrapper.pkl

transformed_commits:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/transformed_data/transformed_commits.pkl

test_transformer:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/models/test_transformer.pkl

tests:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/raw_data/tests.csv

test_parameters:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/transformed_data/test_parameters.pkl

transformed_tests:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/transformed_data/transformed_tests.pkl

augmented_test_parameters:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/transformed_data/augmented_test_parameters.pkl

jira_info:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/raw_data/jira_info.csv

features:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/learning_data/features.pkl

targets:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/learning_data/targets.pkl
