# Data Catalog Smart testing

### Commits
commit_dataset:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/raw_data/commits.csv

transformed_commits:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/transformed_data/transformed_commits.pkl

project_wrapper:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/models/project_wrapper.pkl

lficf_pca_model:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/models/lficf_pca.pkl


### Jira
jira_info:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/raw_data/jira_info.csv


### Tests
tests:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/raw_data/tests.csv

test_parameters:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/transformed_data/test_parameters.pkl

transformed_tests:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/transformed_data/transformed_tests.pkl


### Training
features:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/learning_data/features.pkl

targets:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/learning_data/targets.pkl
