# Data Catalog Smart testing

### Commits
commit_dataset:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/raw_data/commits.csv

transformed_commits:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/transformed_data/transformed_commits.pkl

project_wrapper:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/models/project_wrapper.pkl

lficf_pca_model:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/models/lficf_pca.pkl


### Jira
jira_info:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/raw_data/jira_info.csv


### Tests
historical_tests:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/raw_data/historical_tests.csv

master_tests:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/raw_data/master_tests.csv

validation_tests:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/raw_data/validation_tests.csv

encoded_hitorical_test:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/transformed_data/historical_test_encoded.pkl

encoded_master_tests:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/transformed_data/master_test_encoded.pkl

encoded_validation_tests:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/transformed_data/validation_test_encoded.pkl

fuzzy_encoder:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/models/fuzzy_encoder.pkl

scored_validation_tests:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/transformed_data/scored_validation_tests.csv


### Training
features:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/learning_data/features.pkl

targets:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/learning_data/targets.pkl

commit2test_network:
  type: regtech.datalab.datasets.keras.KerasModelDataSet
  path: data/train_inputs/models/commit2test/commit2test.h5

commit2test_params:
  type: regtech.datalab.datasets.json.JsonDataSet
  path: data/train_inputs/models/commit2test/commit2test.json