# Data Catalog Smart testing
commit_dataset:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/commits.csv

project_wrapper:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/project_wrapper.pkl

transformed_commits:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/transformed_commits.pkl

test_parameters:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/test_parameters.pkl

jira_info:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/jira_info.pkl

augmented_test_parameters:
  type: pandas.CSVDataSet
  filepath: data/train_inputs/augmented_test_parameters.pkl

distributed_tests:
  type: regtech.datalab.datasets.pickle.PickleDataSet
  path: data/train_inputs/distributed_tests.pkl
