# Parameters Smart testing

### Global
path_project: data/train_inputs/git_projects
path_c2v: data/train_inputs/c2v_models/java-large-release/saved_model_iter3.release
path_stopwords: data/nltk_data/stopwords/english
path_test: data/test_data/raw_tests.csv

### Commits
date_start: 2021-01-01
date_end: 2021-09-01
git_options:
  log:
    - '--no-merges'
    - '--full-history'
  diff:
    - '--oneline'
custom_message_regex:
  regfstr_code: (?i)(regsftr\s?\d{2,5})
  alm_code: (?i)(alm\s?\d{2,5})

n_component_lficf: 100
n_commit_group: 100
n_step_commits: 50

### tests
threshold_levenstein: 0.3
threshold_inter: 0.2
threshold_lcs: 0.95
threshold_hamming: 0.95
n_tests: 100
create_random_test: True
create_random_join_info: True
regex_parameters: ((?:[a-z]|[0-9])+)=((?:[a-z]|[0-9])+)
test_parameters:
  - param1=v1
  - param1=v2
  - param1=v3
  - param2=v1
  - param2=v2
  - param3=v1
  - param3=v2
  - param3=v3
  - param3=v4
  - param3=v5
  - param3=v6
  - param4=v1
  - param4=v2
  - param5=<int>
  - param6=v1
  - param6=v2
  - param7=v1
  - param7=v2
  - param7=v3
  - param7=v4
  - param7=v5
  - param8=<int>
  - param9=v1
  - param9=v2

### Training
n_kernels: 200
kernel_size: 1
learning_rate: 0.01
nb_epoch: 1000

### Matching
dictionary_regression:
  alpha: 0.00001
  fit_intercept: True
  normalize: False
  max_iter: 1000